spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api?useSSL=false
    username: root
    password: password
mybatis:
  config-location: classpath:mybatis.xml
debug: true
server:
  port: 8888

